# Generated by Django 2.0.6 on 2018-06-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
