# Generated by Django 2.0.6 on 2018-06-26 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180625_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
