# Generated by Django 2.0.6 on 2018-06-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180626_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=20)),
            ],
        ),
    ]
