# Generated by Django 2.0.6 on 2018-06-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20180626_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
