# Generated by Django 2.0.6 on 2018-06-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_orderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
