# Generated by Django 2.0.6 on 2018-06-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_orderlog_relate_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('md5', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='orderlog',
            name='is_strategy',
            field=models.BooleanField(default=0, verbose_name=False),
            preserve_default=False,
        ),
    ]
