# Generated by Django 2.0.6 on 2018-06-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20180627_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='md5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
