# Generated by Django 2.0.6 on 2018-06-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20180628_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeConfig',
        ),
    ]
