# Generated by Django 2.0.6 on 2018-06-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_delete_strategyorderloop'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='account_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
