# Generated by Django 2.0.6 on 2018-06-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_orderlog_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='update_md5_at',
            field=models.DateTimeField(null=True),
        ),
    ]
