# Generated by Django 2.0.6 on 2018-06-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_account_update_md5_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyOrderLoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('zone_name', models.CharField(max_length=20)),
                ('coin_name', models.CharField(max_length=20)),
                ('percent', models.FloatField()),
            ],
        ),
    ]
