# Generated by Django 2.0.6 on 2018-06-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_strategyorderloop_is_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyorderloop',
            name='point',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
