# Generated by Django 2.0.6 on 2018-06-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_strategyorderloop_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLoopNumbersLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='strategyorderloop',
            name='max_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='strategyorderloop',
            name='min_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='strategyorderloop',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
