# Generated by Django 2.0.6 on 2018-06-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20180630_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
