# Generated by Django 2.0.6 on 2018-07-03 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_reservationorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationorder',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
