# Generated by Django 2.0.6 on 2018-07-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_reservationorder_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationorder',
            name='coin_id',
        ),
        migrations.AddField(
            model_name='reservationorder',
            name='coin_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationorder',
            name='zone_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
