# Generated by Django 2.0.6 on 2018-07-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_reservationorder_reservation_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatFlushLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=20)),
                ('zone_name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('trade_type', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Account')),
            ],
        ),
    ]
